# Use this Blueprint to deploy n8n on Render as a web
# service that uses a Postgres database to store
# workflow data.
#
# This Blueprint uses starter instance types (specified by
# `plan`) for both the web service and the database. You
# can upgrade to paid instance types at any time to
# increase resources.

services:
  - type: web
    plan: starter # Plan Starter para tu servicio web de n8n
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Aquí ya está tu URL asignada por Render. ¡Perfecto!
      - key: WEBHOOK_URL
        value: https://n8n-service-pbqp.onrender.com
      - key: N8N_HOST
        value: https://n8n-service-pbqp.onrender.com

      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production

      # Configuración de autenticación básica (MUY RECOMENDADO por seguridad)
      # Render te pedirá un usuario y contraseña cuando despliegues.
      - key: N8N_BASIC_AUTH_ACTIVE
        value: 'true'
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false

      # Configura tu zona horaria para que n8n muestre los horarios correctos.
      - key: GENERIC_TIMEZONE
        value: America/Argentina/Buenos_Aires

      # Conexión a la base de datos PostgreSQL.
      # Render automáticamente llenará estos valores desde la configuración de tu base de datos.
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port

databases:
  - name: n8n-db
    plan: basic-256mb # Plan Basic-256MB para tu base de datos
    diskSizeGB: 15 # Tamaño de disco para el plan Basic-256MB
    # region: oregon
   
    
   
